name: 'GitHub Actions NPM Package'

on:
  push:
    branches: [master]

jobs:
  init-epm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: pwd
      - run: npm ci
      - run: whereis node
      - run: ls -al ~
      - run: ls -al
      - run: cat ~/.npm

  publish-npm:
    needs: init-epm
    runs-on: ubuntu-latest
    steps:
      - name: 'Log'
        env:
          CC: ${{ toJSON(github) }}
        run: echo "$CC"

      - name: 'Checkout'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      #     registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Run Code
        run: node .github/workflows/notify.js
        env:
          GITHUB: ${{ toJSON(github) }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SIGN: ${{ secrets.FEISHU_SIGN }}
