name: 'GitHub Actions NPM Package'

on:
  push:
    branches: [master]

jobs:
  init-epm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          # registry-url: 'https://registry.epm.edgeros.com'
      - run: pwd
      - run: npm -v
      - run: npm ci
      - run: echo "@edgeros:registry=https://registry.epm.edgeros.com/" > ~/.npmrc
      - run: echo "//registry.epm.edgeros.com/:_password=${{secrets.EPM_TOKEN}}" >> ~/.npmrc
      - run: echo "//registry.epm.edgeros.com/:username=xieyuanbin" >> ~/.npmrc
      - run: echo "//registry.epm.edgeros.com/:email=xieyuanbin@acoinfo.com" >> ~/.npmrc
      - run: echo "//registry.epm.edgeros.com/:always-auth=false" >> ~/.npmrc
      - run: ls -al ~
      - run: cat ~/.npmrc
      - run: npm config list
      - run: npm publish

  publish-npm:
    needs: init-epm
    runs-on: ubuntu-latest
    steps:
      - name: 'Log'
        env:
          CC: ${{ toJSON(github) }}
        run: echo "$CC"

      - name: 'Checkout'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      #     registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Run Code
        run: node .github/workflows/notify.js
        env:
          GITHUB: ${{ toJSON(github) }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SIGN: ${{ secrets.FEISHU_SIGN }}
