name: 'GitHub Actions Send Message to Feishu'

on:
  push:
    branches: [master]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Install node'
        uses: actions/setup-node@v1

      - name: 'Install NPM dependencies'
        run: npm install

      - name: 'Run node'
        run: node notify.js

        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SIGN: ${{ secrets.FEISHU_SIGN }}