name: 'GitHub Actions Send Message to Feishu'

on:
  # push:
  #   branches: [master]
  release:
    types: [created]

jobs:
  send-message-to-feishu:
    runs-on: ubuntu-latest
    steps:
      - name: "Log"
        env:
          CC: ${{ toJSON(github) }}
        run: echo "$CC"

      - uses: actions/checkout@v3

      - name: 'Install node'
        uses: actions/setup-node@v3

      - name: 'Install NPM dependencies'
        run: npm install

      - name: 'Run node'
        run: node notify.js

        env:
          GITHUB: ${{ toJSON(github) }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          FEISHU_SIGN: ${{ secrets.FEISHU_SIGN }}